"""
Parser per estrarre tag strutturati dalla risposta del DM IA:

  <STATE_UPDATE>{...}</STATE_UPDATE>
  <CHAR_UPDATE>{...}</CHAR_UPDATE>
  <ROLL_REQ>{"dice":"1d20+5",...}</ROLL_REQ>
  MAP_START ... MAP_END

Espone anche `clean_text` per rimuovere reasoning/debug dal testo finale.
"""
from __future__ import annotations

import json
import re
from typing import Any

from dnd import rules


# ────────────────────────────────────────────────────────────────────────
# Regex
# ────────────────────────────────────────────────────────────────────────

RE_THINK     = re.compile(r"<think>[\s\S]*?</think>", re.IGNORECASE)
RE_STATE     = re.compile(r"<STATE_UPDATE>([\s\S]*?)</STATE_UPDATE>")
RE_CHAR      = re.compile(r"<CHAR_UPDATE>([\s\S]*?)</CHAR_UPDATE>")
RE_ROLL_REQ  = re.compile(r"<ROLL_REQ>([\s\S]*?)</ROLL_REQ>")
RE_MUSIC     = re.compile(r"<MUSIC>([\s\S]*?)</MUSIC>")
RE_SPRITE    = re.compile(r"<SPRITE>([\s\S]*?)</SPRITE>")
RE_SCENE     = re.compile(r"<SCENE>([\s\S]*?)</SCENE>")
RE_SPELL_CAST = re.compile(r"<SPELL_CAST>([\s\S]*?)</SPELL_CAST>")
RE_MAP       = re.compile(r"MAP_START\s*\n([\s\S]*?)\nMAP_END")
RE_MAP_BLOCK = re.compile(r"MAP_START[\s\S]*?MAP_END\s*", re.IGNORECASE)
RE_DEBUG_LN  = re.compile(r"^\s*\*(?:Calcolo|Formula Base|Dettaglio).*?\*\s*$",
                          re.IGNORECASE | re.MULTILINE)

# Sezioni FASE 3 da nascondere all'utente (sorpresa). Il DM web può scrivere
# le intestazioni in vari modi: con bold (**N. NAME**), heading (### NAME),
# o anche solo numero+keyword PLAIN (es. "2. MAPPA DUNGEON 10×10").
# Sezioni rimosse: MAPPA, LISTA ZONE, MOSTRI, PNG, TESORI, TRAMA, ARCO,
# LEGENDA, BOSS, STAT BLOCK, EPILOGO, RIVELAZIONI.
# Sezione mantenuta: 1 TITOLO + HOOK (presentazione narrativa).
_SECRET_KEYWORDS = (
    r"MAPPA(?:\s+DUNGEON)?(?:\s+\d+\s*[x×]\s*\d+)?",
    r"LISTA\s+ZONE",
    r"ZONE\s+DEL\s+DUNGEON",
    r"ZONE",
    r"MOSTRI",
    r"STAT\s*BLOCK",
    r"PNG",
    r"NPC\b",
    r"TESORI",
    r"TRAMA",
    r"ARCO\s+NARRATIVO",
    r"LEGENDA",
    r"BOSS(?:\s+FINALE)?",
    r"EPILOGO",
    r"RIVELAZIONI",
)
_HDR_KW = "(?:" + "|".join(_SECRET_KEYWORDS) + ")"

# Stop condition (lookahead): match qualsiasi NUOVO header per terminare
# la sezione corrente.
_STOP_AHEAD = (
    r"\n[ \t]*\*\*\s*\d+\s*[.)]"                               # **N. ...
    r"|\n[ \t]*\d+\s*[.)]\s*[A-ZÀ-ÿ]"                          # N. UPPER (plain)
    r"|\n[ \t]*\*\*\s*[A-ZÀ-Ý][A-ZÀ-Ý \t\-]{2,40}\*\*"          # **HEADER**
    r"|\n[ \t]*#{1,4}\s+\S"                                     # ### HEADER
    r"|\n[ \t]*---+\s*\n"                                        # ---
    r"|\Z"                                                       # EOT
)

RE_SECRET_SECTION = re.compile(
    r"(?:^|\n)[ \t]*"
    r"(?:"
        r"\*\*\s*\d+\s*[.)]\s*" + _HDR_KW + r"[^*\n]*\*\*"      # **2. MAPPA**
        r"|"
        r"\*\*\s*" + _HDR_KW + r"[^*\n]*\*\*"                    # **MOSTRI**
        r"|"
        r"#{1,4}\s*" + _HDR_KW + r"[^\n]*"                       # ### MOSTRI
        r"|"
        r"\d+\s*[.)]\s*" + _HDR_KW + r"[^\n]*"                   # 2. MAPPA DUNGEON
        r"|"
        r"" + _HDR_KW + r"[ \t]*$"                               # MOSTRI da solo (riga)
    r")"
    r"[\s\S]*?(?=" + _STOP_AHEAD + r")",
    re.IGNORECASE | re.MULTILINE,
)

# Footer di disclaimer DeepSeek/altre chat web
RE_AI_FOOTER = re.compile(
    r"\n*\s*(?:"
        r"Questa risposta è generata da AI[^\n]*"
        r"|Generated by AI[^\n]*"
        r"|AI[- ]generated[^\n]*"
        r"|This response is AI[- ]generated[^\n]*"
    r")\s*$",
    re.IGNORECASE,
)

# Righe che spoilerano nemici/tesori al giocatore (formato "etichetta: …").
# La FASE 3 mette queste info nelle sezioni segrete; eventuali righe
# sciolte vanno comunque tolte dalla narrazione visibile.
RE_LEAK_LINE = re.compile(
    r"(?im)^[ \t>*_·•\-]*\*{0,2}\s*"
    r"(?:nemici|nemico|mostri|mostro|tesori|tesoro|bottino|loot|"
    r"ricompens[ae]|incontri|avversari)"
    r"[^\n:]{0,28}:.*$"
)


# ────────────────────────────────────────────────────────────────────────
# Pulizia
# ────────────────────────────────────────────────────────────────────────

# Etichette di interfaccia che alcune chat web antepongono alla risposta
# come testo per screen-reader (es. Claude.ai con locale italiano:
# "Claude ha risposto:"). L'estrazione via innerText le cattura: da togliere.
RE_UI_LABEL = re.compile(
    r"(?:^|\n)[ \t]*(?:Claude|Assistant|Assistente|ChatGPT|Gemini|DeepSeek|"
    r"Grok|Qwen)\s+(?:ha\s+(?:risposto|detto|scritto)|said|replied|"
    r"responded)[ \t]*:[ \t]*",
    re.IGNORECASE,
)


def _norm_cmp(s: str) -> str:
    """Forma normalizzata per il CONFRONTO fra testi: senza markdown, senza
    punteggiatura di coda, whitespace collassato, minuscolo. Così due copie
    che differiscono solo per markdown o punteggiatura risultano uguali."""
    s = re.sub(r"[*_`#>~]+", "", s)
    s = re.sub(r"\s+", " ", s).strip().lower()
    return s.rstrip(" .!?,;:—-…")


def _same_text(a: str, b: str) -> bool:
    """True se due testi sono 'la stessa cosa' a meno di markdown,
    punteggiatura di coda o lieve troncamento (copia raddoppiata)."""
    a, b = _norm_cmp(a), _norm_cmp(b)
    if not a or not b:
        return False
    if a == b:
        return True
    lo, hi = (a, b) if len(a) <= len(b) else (b, a)
    return len(lo) >= 25 and hi.startswith(lo) and (len(hi) - len(lo)) <= 4


def _dedup_consecutive(units: list, min_len: int) -> list:
    """Rimuove ogni elemento uguale (per _same_text) a quello tenuto prima.
    Salta il confronto sulle unità troppo corte (sotto min_len)."""
    out: list = []
    for u in units:
        if out and len(_norm_cmp(u)) >= min_len and _same_text(out[-1], u):
            continue
        out.append(u)
    return out


def _dehalve(units: list) -> list:
    """Se `units` è una sequenza raddoppiata [A,B,…][A,B,…], restituisce
    solo la prima metà."""
    m = len(units)
    if m >= 2 and m % 2 == 0:
        first, second = units[: m // 2], units[m // 2:]
        if (all(_same_text(a, b) for a, b in zip(first, second))
                and any(len(_norm_cmp(x)) >= 15 for x in first)):
            return first
    return units


def _collapse_doubled(s: str) -> str:
    """Collassa un testo che è la stessa cosa ripetuta due volte di fila
    (separata da whitespace; la seconda copia può essere markdown grezzo o
    leggermente troncata): restituisce una sola copia."""
    norm = _norm_cmp(s)
    L = len(norm)
    if L < 60:
        return s
    half = L // 2
    for h in range(max(1, half - 6), half + 7):
        if _same_text(norm[:h], norm[h:]):
            # ritaglia la prima copia nel testo ORIGINALE: conta i caratteri
            # di confronto (markdown escluso) finché si raggiunge `h`.
            count, cut, prev_ws = 0, len(s), False
            for i, ch in enumerate(s):
                if ch in "*_`#>~":
                    continue
                ws = ch.isspace()
                if not ws or not prev_ws:
                    count += 1
                prev_ws = ws
                if count >= h:
                    cut = i + 1
                    break
            return s[:cut].strip()
    return s


def _dedup_sentences(block: str) -> str:
    """Dentro un blocco, rimuove le FRASI consecutive duplicate (riga per
    riga). Usato solo sulla narrazione finale (testo già privo di tag)."""
    out_lines = []
    for line in block.split("\n"):
        sents = re.split(r"(?<=[.!?…])\s+", line)
        if len(sents) > 1:
            sents = _dedup_consecutive(sents, min_len=25)
        out_lines.append(" ".join(sents))
    return "\n".join(out_lines)


def _dedup_response(text: str, deep: bool = False) -> str:
    """Collassa le risposte duplicate dalle chat web (es. Claude.ai, che
    rimanda il messaggio raddoppiato — preceduto da un'etichetta UI e con
    una copia in markdown grezzo). Toglie l'etichetta, poi collassa la
    ripetizione a livello di blocco e di intero messaggio. `deep=True`
    aggiunge la dedup a livello di FRASE: usarla SOLO sulla narrazione
    finale (testo già privo di mappa e tag)."""
    if not text:
        return text
    s = RE_UI_LABEL.sub("\n", text).strip()
    blocks = re.split(r"\n{2,}", s)
    if len(blocks) >= 2:
        blocks = _dedup_consecutive(_dehalve(blocks), min_len=15)
        s = "\n\n".join(blocks).strip()
    if deep:
        s = "\n\n".join(_dedup_sentences(b)
                        for b in re.split(r"\n{2,}", s))
    return _collapse_doubled(s)


def clean_text(text: str) -> str:
    """Rimuove blocchi <think>, righe di debug, spazi multipli eccessivi e
    collassa le risposte duplicate (chat web che rimandano il messaggio due
    volte). NON rimuove i tag STATE_UPDATE/CHAR_UPDATE/ROLL_REQ
    (gestiti separatamente)."""
    if not text:
        return ""
    out = RE_THINK.sub("", text)
    out = RE_DEBUG_LN.sub("", out)
    out = re.sub(r"\n{3,}", "\n\n", out)
    out = _dedup_response(out)
    return out.strip()


def strip_tags(text: str) -> str:
    """Rimuove TUTTI i tag strutturati (per la visualizzazione utente)."""
    out = RE_STATE.sub("", text)
    out = RE_CHAR.sub("", out)
    out = RE_ROLL_REQ.sub("", out)
    out = RE_MUSIC.sub("", out)
    out = RE_SPRITE.sub("", out)
    out = RE_SCENE.sub("", out)
    out = RE_SPELL_CAST.sub("", out)
    out = re.sub(r"\n{3,}", "\n\n", out)
    return out.strip()


def strip_narrative(text: str) -> str:
    """
    Versione "solo narrazione" del testo, per il display chat.
    Rimuove: tag strutturati, blocchi MAP_START..END, sezioni segrete
    della FASE 3 (mappa, zone, mostri, PNG, tesori, trama, boss, epilogo),
    e footer AI-generated.
    Mantiene la narrazione (titolo+hook, dialoghi, descrizioni delle scene).
    """
    out = RE_STATE.sub("", text)
    out = RE_CHAR.sub("", out)
    out = RE_ROLL_REQ.sub("", out)
    out = RE_MUSIC.sub("", out)
    out = RE_SPRITE.sub("", out)
    out = RE_SCENE.sub("", out)
    out = RE_SPELL_CAST.sub("", out)
    out = RE_MAP_BLOCK.sub("", out)
    out = RE_AI_FOOTER.sub("", out)
    # applica più volte: sezioni adiacenti possono lasciare residui che
    # diventano stop-anchor per altre sezioni al passaggio successivo
    for _ in range(3):
        new_out = RE_SECRET_SECTION.sub("", out)
        if new_out == out:
            break
        out = new_out
    # righe sciolte che spoilerano nemici/tesori
    out = RE_LEAK_LINE.sub("", out)
    # rimuovi separatori "---" rimasti orfani
    out = re.sub(r"(?m)^\s*---+\s*$", "", out)
    out = re.sub(r"\n{3,}", "\n\n", out)
    # Dedup FINALE della narrazione: la chat web può raddoppiare il
    # messaggio (con un blocco tag MAP/STATE FRA le due copie, oppure
    # ripetendo solo l'ultima frase). Qui i tag sono già stati tolti →
    # dedup profonda (blocco + frase) sul testo di pura narrazione.
    out = _dedup_response(out, deep=True)
    return out.strip()


# ────────────────────────────────────────────────────────────────────────
# Estrazione tag
# ────────────────────────────────────────────────────────────────────────

def _lenient_json(raw: str) -> Any:
    """Ultimo tentativo: ripara gli errori JSON tipici dei modelli web —
    tag rimasti incollati dentro il payload (es. `<MUSIC>{<MUSIC>{...`),
    graffe doppie, chiavi senza virgolette, virgole finali. Usato SOLO
    dopo che il parsing stretto è fallito."""
    s = (raw or "").strip()
    # frammenti di tag rimasti DENTRO il payload (<MUSIC>, </SCENE>, ...)
    s = re.sub(r"</?[A-Za-z_]+>", "", s)
    if "{" not in s or "}" not in s:
        return None
    # isola dal primo { all'ultimo }
    s = s[s.index("{"): s.rindex("}") + 1]
    # graffe di apertura/chiusura duplicate adiacenti (es. "{{" → "{")
    s = re.sub(r"\{(?:\s*\{)+", "{", s)
    s = re.sub(r"\}(?:\s*\})+", "}", s)
    # chiavi non quotate: {mood:  / ,bpm:  →  {"mood":  / ,"bpm":
    s = re.sub(r'([{,]\s*)([A-Za-z_]\w*)(\s*:)', r'\1"\2"\3', s)
    # virgole finali prima di } o ]
    s = re.sub(r",(\s*[}\]])", r"\1", s)
    try:
        return json.loads(s)
    except (ValueError, json.JSONDecodeError):
        return None


def _safe_json(payload: str) -> Any:
    try:
        return json.loads(payload.strip())
    except (json.JSONDecodeError, ValueError):
        pass
    # tentativo: estrai il primo oggetto valido
    try:
        start = payload.index("{")
        end = payload.rindex("}") + 1
        return json.loads(payload[start:end])
    except (ValueError, json.JSONDecodeError):
        pass
    # ultimo tentativo: ripara gli errori JSON comuni dei modelli web
    return _lenient_json(payload)


def _as_dicts(obj: Any) -> list[dict]:
    """Normalizza un payload JSON in lista di dict.
    Il DM può emettere un singolo oggetto {...} o un array [{...},{...}]."""
    if isinstance(obj, dict):
        return [obj]
    if isinstance(obj, list):
        return [x for x in obj if isinstance(x, dict)]
    return []


def extract_state(text: str) -> dict | None:
    """Restituisce il PRIMO <STATE_UPDATE> trovato come dict, o None.
    Tollera payload array: unisce gli oggetti in un unico dict."""
    m = RE_STATE.search(text)
    if not m:
        return None
    dicts = _as_dicts(_safe_json(m.group(1)))
    if not dicts:
        return None
    upd: dict = {}
    for d in dicts:
        upd.update(d)
    if isinstance(upd.get("map_ascii"), str):
        upd["map_ascii"] = upd["map_ascii"].replace("\\n", "\n")
    return upd


def extract_chars(text: str) -> list[dict]:
    """Tutti i <CHAR_UPDATE> come lista di dict (gestisce anche array)."""
    out: list[dict] = []
    for m in RE_CHAR.finditer(text):
        out.extend(_as_dicts(_safe_json(m.group(1))))
    return out


def extract_map(text: str) -> str | None:
    m = RE_MAP.search(text)
    return m.group(1).rstrip() if m else None


def extract_music(text: str) -> list[dict]:
    """Tutti i <MUSIC> come lista di dict: colonne sonore generate dal DM."""
    out: list[dict] = []
    for m in RE_MUSIC.finditer(text):
        out.extend(_as_dicts(_safe_json(m.group(1))))
    return out


# Palette pixel-art a 16 colori: ogni pixel è UNA cifra esadecimale.
_HEX = set("0123456789abcdef")


def _normalize_grid(rows: Any, size: int) -> list[str] | None:
    """Normalizza una griglia pixel-art a `size`×`size` cifre esadecimali
    (palette 16 colori). Righe/colonne mancanti riempite con '0', eccedenze
    tagliate, caratteri non validi → '0'. None se `rows` non è una lista."""
    if not isinstance(rows, list):
        return None
    grid: list[str] = []
    for i in range(size):
        row = str(rows[i]).lower() if i < len(rows) else ""
        row = "".join(c if c in _HEX else "0" for c in row)[:size]
        grid.append(row.ljust(size, "0"))
    return grid


def extract_sprites(text: str) -> dict[str, list[str]]:
    """Tutti i <SPRITE> come dict {id: griglia 10×10}. Il DM disegna in
    pixel-art (palette fantasy 16 colori, cifre esadecimali) gli elementi
    della scena; `id` è il carattere di cella che la sprite raffigura."""
    out: dict[str, list[str]] = {}
    for m in RE_SPRITE.finditer(text):
        for d in _as_dicts(_safe_json(m.group(1))):
            sid = str(d.get("id") or "").strip()
            grid = _normalize_grid(d.get("rows"), 10)
            if sid and grid:
                out[sid] = grid
    return out


# Lato dell'illustrazione di scena (griglia pixel-art quadrata).
SCENE_SIZE = 64


def extract_scene(text: str) -> dict | None:
    """L'ULTIMO <SCENE> del testo come dict {rows: griglia 64×64,
    caption: str}. Il DM disegna in pixel-art un'illustrazione della
    situazione di gioco corrente (non la mappa dall'alto: la scena in
    prospettiva). None se assente o malformato."""
    last: Any = None
    for m in RE_SCENE.finditer(text):
        d = _safe_json(m.group(1))
        if isinstance(d, dict):
            last = d
    if not isinstance(last, dict):
        return None
    grid = _normalize_grid(last.get("rows"), SCENE_SIZE)
    if not grid:
        return None
    return {"rows": grid, "caption": str(last.get("caption") or "").strip()}


def extract_roll_requests(text: str) -> list[dict]:
    """Tutti i <ROLL_REQ> come lista di dict payload (gestisce anche array)."""
    out: list[dict] = []
    for m in RE_ROLL_REQ.finditer(text):
        out.extend(_as_dicts(_safe_json(m.group(1))))
    return out


def extract_spell_casts(text: str) -> list[dict]:
    """Tutti i <SPELL_CAST> come lista di dict {by, spell, level}: il DM
    li emette quando un PG/PNG lancia un incantesimo, così il sistema può
    scalare lo slot corrispondente sulla scheda."""
    out: list[dict] = []
    for m in RE_SPELL_CAST.finditer(text):
        out.extend(_as_dicts(_safe_json(m.group(1))))
    return out


# ────────────────────────────────────────────────────────────────────────
# Risoluzione ROLL_REQ
# ────────────────────────────────────────────────────────────────────────

def resolve_roll_requests(
    text: str, human_names: list[str] | None = None
) -> tuple[str, list[dict], list[dict]]:
    """
    Esegue i <ROLL_REQ> del testo. I tiri il cui campo `by` corrisponde a un
    PG UMANO NON vengono eseguiti: spettano al giocatore (riquadro dadi).
    Restituisce:
      - testo con i tag sostituiti dal risultato inline leggibile
      - lista dei risultati eseguiti (dict) per il log e la conversazione
      - lista dei tiri in attesa (payload dict) che deve tirare il giocatore
    """
    human = {(n or "").strip().lower() for n in (human_names or []) if n}
    results: list[dict] = []
    pending: list[dict] = []

    def _sub(match: re.Match) -> str:
        payloads = _as_dicts(_safe_json(match.group(1)))
        if not payloads:
            return f"[ROLL_REQ malformata: {match.group(1)[:60]}]"
        parts: list[str] = []
        for payload in payloads:
            by = (payload.get("by") or "").strip()
            if by and by.lower() in human:
                # tiro di un PG umano: lo lancia il giocatore, non il sistema
                pending.append(payload)
                parts.append(_format_roll_pending(payload))
                continue
            try:
                r = rules.parse_roll_request(payload)
            except ValueError as e:
                parts.append(f"[ROLL_REQ errore: {e}]")
                continue
            info = r.to_dict()
            # campi extra utili al log
            info["target"] = payload.get("target")
            info["by"] = payload.get("by")
            results.append(info)
            parts.append(_format_roll_inline(r, payload))
        return " ".join(parts)

    new_text = RE_ROLL_REQ.sub(_sub, text)
    return new_text, results, pending


def _format_roll_pending(payload: dict) -> str:
    """Messaggio inline per un tiro che deve lanciare il giocatore umano."""
    by = payload.get("by") or "Giocatore"
    dice = payload.get("dice") or payload.get("expr") or "1d20"
    reason = payload.get("reason") or ""
    target = payload.get("target")
    tag = ""
    if payload.get("advantage"):
        tag = " con vantaggio"
    elif payload.get("disadvantage"):
        tag = " con svantaggio"
    extras = []
    if reason:
        extras.append(reason)
    if target:
        extras.append(f"vs {target}")
    suffix = f" — *{' · '.join(extras)}*" if extras else ""
    return f"**🎲 {by}, tira {dice}{tag}** dal riquadro dadi{suffix}"


def _format_roll_inline(r: rules.RollResult, payload: dict) -> str:
    by = payload.get("by")
    target = payload.get("target")
    parts = [f"**🎲 {r.expr}"]
    if r.advantage:
        parts.append(" (vant)")
    if r.disadvantage:
        parts.append(" (svant)")
    parts.append(f" = **{r.total}**")
    if r.is_crit:
        parts.append(" ✦CRITICO")
    if r.is_fumble:
        parts.append(" ✗FUMBLE")
    extras = []
    if r.reason:
        extras.append(r.reason)
    if by:
        extras.append(f"da {by}")
    if target:
        extras.append(f"vs {target}")
    if extras:
        parts.append(f" — *{' · '.join(extras)}*")
    rolls_s = "+".join(str(x) for x in r.rolls)
    mod_s = f"{r.modifier:+d}" if r.modifier else ""
    parts.append(f" [{rolls_s}{mod_s}]")
    return "".join(parts)


# ────────────────────────────────────────────────────────────────────────
# Applicazione a game_state
# ────────────────────────────────────────────────────────────────────────

def apply_state_update(state: dict, update: dict) -> None:
    """Aggiorna game_state con i campi presenti nello STATE_UPDATE."""
    if not isinstance(update, dict) or not update:
        return
    # players_hp è un caso speciale: aggiorna sheet di ogni player
    if "players_hp" in update:
        for p in state.get("players", []):
            name = p.get("name", "")
            if name in update["players_hp"]:
                hp = update["players_hp"][name]
                if isinstance(hp, dict):
                    sheet = p.setdefault("sheet", {})
                    sheet_hp = sheet.setdefault("hp", {})
                    sheet_hp.update(hp)
                    if sheet_hp.get("current", 1) <= 0:
                        sheet["status"] = "down"
                    else:
                        sheet["status"] = "alive"
        update = {k: v for k, v in update.items() if k != "players_hp"}
    state.update(update)


def _deep_merge(dst: dict, src: dict) -> None:
    """Fonde `src` dentro `dst` in-place. I dict annidati (hp, stats,
    death_saves) vengono uniti campo per campo invece di essere sostituiti:
    un CHAR_UPDATE parziale come {"hp":{"current":8}} NON cancella hp.max."""
    for k, v in src.items():
        if isinstance(v, dict) and isinstance(dst.get(k), dict):
            _deep_merge(dst[k], v)
        else:
            dst[k] = v


def apply_char_updates(state: dict, updates: list[dict],
                       on_persist: Any = None) -> None:
    """Aggiorna o inserisce le schede personaggio. Se `on_persist` callable,
    viene chiamato con ogni scheda completa (utile per upsert su file).

    Il merge è profondo: un update parziale del DM (es. solo i danni su
    hp.current) NON azzera gli altri campi della scheda né hp.max."""
    for char in updates:
        if not isinstance(char, dict):
            continue
        name = (char.get("name") or "").strip()
        if not name:
            continue
        hp = char.get("hp", {})
        if isinstance(hp, dict):
            cur = hp.get("current")
            if cur is not None and cur <= 0:
                hp["current"] = 0
                char["status"] = "down" if not char.get("death_saves", {}).get("dead") else "dead"
            elif cur is not None and cur > 0:
                char.setdefault("status", "alive")

        player = next(
            (p for p in state.get("players", [])
             if (p.get("name") or "").lower() == name.lower()),
            None,
        )
        if player is None:
            player = {"name": name, "type": "human", "sheet": {}}
            state.setdefault("players", []).append(player)
        sheet = player.setdefault("sheet", {})
        _deep_merge(sheet, char)

        if callable(on_persist):
            try:
                # persiste la scheda COMPLETA fusa, non l'update parziale
                on_persist(dict(sheet))
            except Exception as e:
                print(f"[parser] persist fallita per {name}: {e}", flush=True)


def apply_spell_casts(state: dict, casts: list[dict]) -> list[dict]:
    """Consuma uno slot incantesimo per ogni <SPELL_CAST> di livello ≥ 1.

    I trucchetti (livello 0) sono a volontà: NON consumano slot.
    Restituisce un report con un dict per ogni lancio:
      {by, spell, level, ok, detail}
    `ok=False` se il PG non esiste, non è incantatore, non ha uno slot di
    quel livello, oppure ha già esaurito gli slot di quel livello — in tal
    caso lo slot NON viene scalato e il DM va avvisato (l'incantesimo non
    può essere lanciato)."""
    results: list[dict] = []
    if not casts:
        return results
    for c in casts:
        if not isinstance(c, dict):
            continue
        by = (c.get("by") or c.get("name") or c.get("character") or "").strip()
        spell = (c.get("spell") or c.get("name") or "").strip()
        try:
            level = int(c.get("level", 0) or 0)
        except (TypeError, ValueError):
            level = 0
        rec = {"by": by, "spell": spell, "level": level, "ok": True, "detail": ""}
        if level <= 0:
            rec["detail"] = "trucchetto — a volontà, nessuno slot consumato"
            results.append(rec)
            continue
        player = next(
            (p for p in state.get("players", [])
             if (p.get("name") or "").lower() == by.lower()),
            None,
        )
        if player is None:
            rec["ok"] = False
            rec["detail"] = "personaggio non trovato"
            results.append(rec)
            continue
        sheet = player.setdefault("sheet", {})
        spells = sheet.get("spells")
        slots = spells.get("slots") if isinstance(spells, dict) else None
        if not isinstance(slots, dict) or not slots:
            rec["ok"] = False
            rec["detail"] = "il personaggio non è un incantatore"
            results.append(rec)
            continue
        sl = slots.get(str(level))
        if not isinstance(sl, dict):
            rec["ok"] = False
            rec["detail"] = f"nessuno slot di livello {level}"
            results.append(rec)
            continue
        mx = max(0, int(sl.get("max", 0) or 0))
        used = max(0, int(sl.get("used", 0) or 0))
        if used >= mx:
            rec["ok"] = False
            rec["detail"] = f"slot di livello {level} esauriti ({used}/{mx})"
            results.append(rec)
            continue
        sl["used"] = used + 1
        rec["detail"] = f"slot L{level} consumato — restano {mx - sl['used']}/{mx}"
        results.append(rec)
    return results


# Mood validi per il motore musicale (slot rimpiazzabili dal DM).
_MUSIC_MOODS = {"menu", "generation", "explore", "social", "combat"}
_MUSIC_FIELDS = ("bpm", "wave", "cutoff", "gain", "pad", "bass", "lead", "drum")


def apply_music_update(state: dict, updates: list[dict]) -> None:
    """Registra le colonne sonore generate dal DM in `state['music']`,
    indicizzate per mood. Il frontend le passa al motore audio generativo.

    Ogni <MUSIC> rimpiazza lo slot del mood indicato (default: 'explore')."""
    if not updates:
        return
    music = state.setdefault("music", {})
    for u in updates:
        if not isinstance(u, dict):
            continue
        mood = (u.get("mood") or "explore").strip().lower()
        if mood not in _MUSIC_MOODS:
            mood = "explore"
        tune = {k: u[k] for k in _MUSIC_FIELDS if k in u}
        if tune:
            music[mood] = tune


def apply_sprites(state: dict, sprites: dict) -> None:
    """Registra/aggiorna le sprite pixel-art generate dal DM in
    `state['sprites']`, indicizzate per carattere di cella. Il frontend le
    usa per disegnare la mappa (con fallback su una sprite di default)."""
    if not sprites:
        return
    store = state.setdefault("sprites", {})
    for sid, grid in sprites.items():
        if isinstance(grid, list) and grid:
            store[sid] = grid


def apply_scene(state: dict, scene: dict | None) -> None:
    """Registra in `state['scene_art']` l'illustrazione pixel-art della
    scena corrente generata dal DM (griglia 32×32 + didascalia)."""
    if scene and scene.get("rows"):
        state["scene_art"] = scene


__all__ = [
    "clean_text", "strip_tags", "strip_narrative",
    "extract_state", "extract_chars", "extract_map", "extract_music",
    "extract_sprites", "extract_scene", "extract_roll_requests",
    "extract_spell_casts", "resolve_roll_requests",
    "apply_state_update", "apply_char_updates", "apply_spell_casts",
    "apply_music_update", "apply_sprites", "apply_scene", "_deep_merge",
]
